generate_names:
  description: >
    Based on the user's initial company name idea, generate a list of 20 unique, brandable company name suggestions. 
    Make the names appealing, easy to remember, and suitable for incorporation in India.
    Avoid common names that may likely be taken already.
    
    Original Idea: {initial_name}
  expected_output: >
    A list of 20 brandable company name suggestions based on "{initial_name}".

check_mca_availability:
  description: >
    For each of the 20 suggested names, check the MCA company name database to determine if they are available for incorporation.
    Return a filtered list with only the names that are allowed for incorporation.

    The tool `MCANameCheckerTool` will be available to help you verify names.
  expected_output: >
    A list of company names that are available as per the MCA (Ministry of Corporate Affairs) name availability check.
